# Generated by Django 3.1.7 on 2021-03-24 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_remove_metadata_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='judul',
            new_name='title',
        ),
        migrations.AddField(
            model_name='metadata',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metadata',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
