# Generated by Django 3.1.7 on 2021-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20210324_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
