# Generated by Django 3.1.7 on 2021-03-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20210324_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
